# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import lamp_pb2 as lamp__pb2


class LampStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.turnOn = channel.unary_unary(
                '/Lamp/turnOn',
                request_serializer=lamp__pb2.LampStatus.SerializeToString,
                response_deserializer=lamp__pb2.LampStatus.FromString,
                )
        self.turnOff = channel.unary_unary(
                '/Lamp/turnOff',
                request_serializer=lamp__pb2.LampStatus.SerializeToString,
                response_deserializer=lamp__pb2.LampStatus.FromString,
                )
        self.requestInfo = channel.unary_unary(
                '/Lamp/requestInfo',
                request_serializer=lamp__pb2.LampInfoParams.SerializeToString,
                response_deserializer=lamp__pb2.LampStatus.FromString,
                )


class LampServicer(object):
    """Missing associated documentation comment in .proto file."""

    def turnOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def turnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def requestInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LampServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'turnOn': grpc.unary_unary_rpc_method_handler(
                    servicer.turnOn,
                    request_deserializer=lamp__pb2.LampStatus.FromString,
                    response_serializer=lamp__pb2.LampStatus.SerializeToString,
            ),
            'turnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.turnOff,
                    request_deserializer=lamp__pb2.LampStatus.FromString,
                    response_serializer=lamp__pb2.LampStatus.SerializeToString,
            ),
            'requestInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.requestInfo,
                    request_deserializer=lamp__pb2.LampInfoParams.FromString,
                    response_serializer=lamp__pb2.LampStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lamp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Lamp(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def turnOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lamp/turnOn',
            lamp__pb2.LampStatus.SerializeToString,
            lamp__pb2.LampStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def turnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lamp/turnOff',
            lamp__pb2.LampStatus.SerializeToString,
            lamp__pb2.LampStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def requestInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Lamp/requestInfo',
            lamp__pb2.LampInfoParams.SerializeToString,
            lamp__pb2.LampStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
