version: "3.4"
volumes:
  kafka-data:
    driver: local
  zookeeper-data:
    driver: local
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    ports:
      - "2181:2181"
    depends_on:
      - kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    volumes:
      - zookeeper-data:/var/run/docker.sock

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "${KAFKA_PORT}:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:${KAFKA_PORT}
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://${LOCAL_IP}:${KAFKA_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    entrypoint: /scripts/create-topics.sh
    volumes:
      - kafka-data:/var/run/docker.sock
      - ./scripts/kafka/:/scripts/

  kafka-ui:
    image: tchiotludo/kafkahq
    depends_on:
      - kafka
    environment:
      KAFKAHQ_CONFIGURATION: |
        kafkahq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
          security:
            basic-auth:
              root:
                password: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8'
                roles:
                  - topic/read
                  - topic/insert
                  - topic/delete
                  - topic/config/update
                  - node/read
                  - node/config/update
                  - topic/data/read
                  - topic/data/insert
                  - topic/data/delete
                  - group/read
                  - group/delete
                  - group/offsets/update
                  - registry/read
                  - registry/insert
                  - registry/update
                  - registry/delete
                  - registry/version/delete
            default-roles:
              - node/read
    ports:
      - 8089:8080
