# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import air_cond_pb2 as air__cond__pb2


class AirCondStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.turnOn = channel.unary_unary(
                '/AirCond/turnOn',
                request_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
                response_deserializer=air__cond__pb2.AirCondStatus.FromString,
                )
        self.turnOff = channel.unary_unary(
                '/AirCond/turnOff',
                request_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
                response_deserializer=air__cond__pb2.AirCondStatus.FromString,
                )
        self.changeTemperature = channel.unary_unary(
                '/AirCond/changeTemperature',
                request_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
                response_deserializer=air__cond__pb2.AirCondStatus.FromString,
                )
        self.requestInfo = channel.unary_unary(
                '/AirCond/requestInfo',
                request_serializer=air__cond__pb2.AirCondInfoParams.SerializeToString,
                response_deserializer=air__cond__pb2.AirCondStatus.FromString,
                )


class AirCondServicer(object):
    """Missing associated documentation comment in .proto file."""

    def turnOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def turnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def changeTemperature(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def requestInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AirCondServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'turnOn': grpc.unary_unary_rpc_method_handler(
                    servicer.turnOn,
                    request_deserializer=air__cond__pb2.AirCondStatus.FromString,
                    response_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
            ),
            'turnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.turnOff,
                    request_deserializer=air__cond__pb2.AirCondStatus.FromString,
                    response_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
            ),
            'changeTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.changeTemperature,
                    request_deserializer=air__cond__pb2.AirCondStatus.FromString,
                    response_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
            ),
            'requestInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.requestInfo,
                    request_deserializer=air__cond__pb2.AirCondInfoParams.FromString,
                    response_serializer=air__cond__pb2.AirCondStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AirCond', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AirCond(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def turnOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AirCond/turnOn',
            air__cond__pb2.AirCondStatus.SerializeToString,
            air__cond__pb2.AirCondStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def turnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AirCond/turnOff',
            air__cond__pb2.AirCondStatus.SerializeToString,
            air__cond__pb2.AirCondStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def changeTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AirCond/changeTemperature',
            air__cond__pb2.AirCondStatus.SerializeToString,
            air__cond__pb2.AirCondStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def requestInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AirCond/requestInfo',
            air__cond__pb2.AirCondInfoParams.SerializeToString,
            air__cond__pb2.AirCondStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
