# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: humidifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10humidifier.proto\"\"\n\x10HumidifierStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x16\n\x14HumidifierInfoParams2\xac\x01\n\nHumidifier\x12\x30\n\x06turnOn\x12\x11.HumidifierStatus\x1a\x11.HumidifierStatus\"\x00\x12\x31\n\x07turnOff\x12\x11.HumidifierStatus\x1a\x11.HumidifierStatus\"\x00\x12\x39\n\x0brequestInfo\x12\x15.HumidifierInfoParams\x1a\x11.HumidifierStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'humidifier_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HUMIDIFIERSTATUS']._serialized_start=20
  _globals['_HUMIDIFIERSTATUS']._serialized_end=54
  _globals['_HUMIDIFIERINFOPARAMS']._serialized_start=56
  _globals['_HUMIDIFIERINFOPARAMS']._serialized_end=78
  _globals['_HUMIDIFIER']._serialized_start=81
  _globals['_HUMIDIFIER']._serialized_end=253
# @@protoc_insertion_point(module_scope)
