# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lamp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nlamp.proto\"\x1c\n\nLampStatus\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x10\n\x0eLampInfoParams2\x82\x01\n\x04Lamp\x12$\n\x06turnOn\x12\x0b.LampStatus\x1a\x0b.LampStatus\"\x00\x12%\n\x07turnOff\x12\x0b.LampStatus\x1a\x0b.LampStatus\"\x00\x12-\n\x0brequestInfo\x12\x0f.LampInfoParams\x1a\x0b.LampStatus\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lamp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LAMPSTATUS']._serialized_start=14
  _globals['_LAMPSTATUS']._serialized_end=42
  _globals['_LAMPINFOPARAMS']._serialized_start=44
  _globals['_LAMPINFOPARAMS']._serialized_end=60
  _globals['_LAMP']._serialized_start=63
  _globals['_LAMP']._serialized_end=193
# @@protoc_insertion_point(module_scope)
